### PR TITLE
Update ldap.rb to allow unencrypted LDAP Access

### PR DESCRIPTION
**Pull request by Shaeli**
The code is failing when connecting to an LDAP with no encryption enabled
```
vendor/gems/ruby/3.1.0/gems/net-ldap-0.17.1/lib/net/ldap/connection.rb:72:in `open_connection': unsupported encryption method  (Net::LDAP::Error)
```
The "nil" `encryption` method doesn't exist, to not use encryption, we can just omit the `encryption` key in the options hash

See https://www.rubydoc.info/gems/net-ldap/Net%2FLDAP:initialize for more info

### CODE REVIEW

**Review by cwage — APPROVED** [review]

**Review by cwage — APPROVED** [review]

**Review by DanHoerst — APPROVED** [review]

**Comment by DanHoerst** [comment]
@Shaeli do you have a Rubygems account? I'll need to give you push access before you can run `scripts/release`

**Comment by Shaeli** [comment]
@DanHoerst I don't have one but I can create one

**Review by GrantBirki — APPROVED** [review]

**Comment by GrantBirki** [comment]
I have some changes coming up and would like to get this merged for you so I don't leave this PR in a state of wild merge conflicts.

@DanHoerst I have a RubyGems account and can merge this, then run `script/release` to get this over the finish line.

My account is: https://rubygems.org/profiles/GrantBirki

**Comment by DanHoerst** [comment]
@GrantBirki I added you as an owner to https://rubygems.org/gems/entitlements, https://rubygems.org/gems/entitlements-app, https://rubygems.org/gems/entitlements-github-plugin and https://rubygems.org/gems/entitlements-gitrepo-auditor-plugin

**Pull request merged**
